apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: demonset-ds
  labels:
    app: demonset
spec:
  minReadySeconds: 30
  template:
    metadata:
      name: demonset-ds
      labels:
        app: demonset
        ver: lts
    spec:
      containers:
        - name: alpine
          image: alpine:3
          command:
            - sleep
              "1d"      
  selector:
    matchLabels:
      app: demonset
    