
apiVersion: v1
kind: Pod
metadata:
  name: nginx-test
  labels:
    app: nginx
    ver: "1.23"
spec:
  initContainers:
    - name: init-cont1
      image: alpine:3
      command:
        - sleep
        - "30"
  containers:
  - name: nginx
    image: nginx:1.23
    ports:
      - containerPort: 80
        protocol: TCP