apiVersion: v1
kind: Service
metadata:
  name: demonset-svc
spec:
  type: NodePort
  selector:
    app: demonset
  ports:
    - port: 32003
      targetPort: 80
      nodePort: 32005
      protocol: TCP